image:
  repository: "us-central1-docker.pkg.dev/krai-project-490112/krai/krai-backend"
  tag: "5bff581"
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    memory: 256Mi
    cpu: 250m
  requests:
    memory: 64Mi
    cpu: 25m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

serviceAccount:
  name: krai
  gcpServiceAccount: "krai-app@krai-project-490112.iam.gserviceaccount.com"

env:
  GOOGLE_CLOUD_PROJECT: "krai-project-490112"
  GCS_BUCKET: "krai-project-490112-krai-bucket"
  PUBSUB_TOPIC: "krai-jobs"
  PUBSUB_SUBSCRIPTION: "krai-jobs-sub"
  GOOGLE_CLIENT_ID: "801062806309-2mkr2ikjl53ore594ql98dlai7beok5u.apps.googleusercontent.com"

worker:
  replicaCount: 1
  resources:
    limits:
      memory: 512Mi
      cpu: 250m
    requests:
      memory: 128Mi
      cpu: 25m
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    pollingInterval: 15
    cooldownPeriod: 60
    messagesPerWorker: "5"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
