image:
  repository: "us-central1-docker.pkg.dev/krai-project-490112/krai/krai-frontend"
  tag: "158fa5a"
  pullPolicy: Always

replicaCount: 0

resources:
  limits:
    memory: 128Mi
    cpu: 100m
  requests:
    memory: 32Mi
    cpu: 10m

autoscaling:
  enabled: false
  minReplicas: 0
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

env:
  REACT_APP_API_URL: "http://krai.krai-backend.svc.cluster.local"
  REACT_APP_API_KEY: "demo-key-change-me"
