image:
  repository: "us-central1-docker.pkg.dev/krai-project-490112/krai/krai-frontend"
  tag: "951dd57"
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    memory: 128Mi
    cpu: 100m
  requests:
    memory: 32Mi
    cpu: 10m

autoscaling:
  enabled: false
  minReplicas: 0
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

env:
  REACT_APP_API_URL: "http://136.111.136.139"
  REACT_APP_API_KEY: ""
  REACT_APP_GOOGLE_CLIENT_ID: "801062806309-2mkr2ikjl53ore594ql98dlai7beok5u.apps.googleusercontent.com"
