apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.env.GOOGLE_CLOUD_PROJECT }}
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: krai-gke
          clusterProjectID: {{ .Values.env.GOOGLE_CLOUD_PROJECT }}
          serviceAccountRef:
            name: krai-eso
            namespace: {{ .Release.Namespace }}
