apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: krai-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: krai-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: krai-api-key
