apiVersion: v1
kind: Service
metadata:
  name: krai
  labels:
    app: krai
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: krai
    component: api
