apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: krai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/red512/krai-gitops
    targetRevision: HEAD
    path: helm/krai-helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: krai-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
