keda:
  serviceAccount:
    operator:
      annotations:
        iam.gke.io/gcp-service-account: keda-operator@krai-project-490112.iam.gserviceaccount.com
  resources:
    operator:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    metricServer:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  logging:
    operator:
      level: info
